@startuml DiagramaClassesValiMarket

class Produto {
  nome: String
  validade: Date
  preco: float
  precoDesconto: float
}

class Empresa {
  nome: String
}

class Usuario {
  nome: String
  email: String
}

class Sistema {
  cadastrarProduto(produto: Produto)
  listarProdutos(): List<Produto>
  listarProdutosProximos(): List<Produto>
}

Empresa "1" o-- "*" Produto
Usuario --> Produto
Sistema --> Produto
Sistema --> Empresa
Sistema --> Usuario

@enduml