@startuml DiagramaSequenciaValiMarket

actor Empresa
participant Sistema
actor Cliente

Empresa -> Sistema: cadastrarProduto()
Sistema -> Sistema: verificarValidade()
Sistema -> Cliente: exibirProdutos()

@enduml